"""
Module 4: Report Generator
- Professional HTML + TXT security reports
- SOC-ready format
"""

import os
from datetime import datetime

def generate_report(target, network_cameras, vuln_results, password_results, risk_score):
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    txt_path  = f"reports/cctvguard_report_{timestamp}.txt"
    html_path = f"reports/cctvguard_report_{timestamp}.html"

    _write_txt(txt_path, target, network_cameras, vuln_results, password_results, risk_score, timestamp)
    _write_html(html_path, target, network_cameras, vuln_results, password_results, risk_score, timestamp)

    return html_path, txt_path


def _risk_level(score):
    if score >= 30: return "CRITICAL RISK"
    if score >= 20: return "HIGH RISK"
    if score >= 10: return "MEDIUM RISK"
    return "LOW RISK"


def _write_txt(path, target, cameras, vulns, passwords, score, ts):
    level = _risk_level(score)
    lines = [
        "=" * 70,
        "           CCTVGuard — SECURITY ASSESSMENT REPORT",
        "=" * 70,
        f"Target      : {target}",
        f"Date        : {ts}",
        f"Risk Score  : {score}/100",
        f"Risk Level  : {level}",
        "=" * 70,
        "",
        "[ 1. CAMERAS DISCOVERED ]",
        "-" * 40,
    ]
    for cam in cameras:
        lines.append(f"  IP: {cam['ip']} | Brand: {cam['brand']} | Ports: {cam['open_ports']}")
        lines.append(f"  RTSP: {'YES' if cam['rtsp_available'] else 'NO'} | Web: {'YES' if cam['has_web_interface'] else 'NO'}")
        lines.append("")

    lines += ["", "[ 2. VULNERABILITY FINDINGS ]", "-" * 40]
    for v in vulns:
        status = "VULNERABLE" if v["status"] == "FAIL" else "PROTECTED"
        lines.append(f"  [{v['severity']}] {v['title']} — {status}")
        lines.append(f"    {v['description']}")
        lines.append("")

    lines += ["", "[ 3. PASSWORD SCAN RESULTS ]", "-" * 40]
    if passwords.get("vulnerable"):
        lines.append(f"  [CRITICAL] Default credentials FOUND!")
        for cred in passwords.get("credentials_found", []):
            lines.append(f"    Credentials: {cred}")
    else:
        lines.append("  [PASS] No default credentials found")

    lines += [
        "", "[ 4. RECOMMENDATIONS ]", "-" * 40,
        "  1. Change default credentials immediately",
        "  2. Update firmware to latest version",
        "  3. Disable Telnet and unused services",
        "  4. Enable HTTPS — disable HTTP",
        "  5. Use VPN for remote camera access",
        "  6. Segment cameras on separate VLAN",
        "  7. Disable UPnP to prevent internet exposure",
        "  8. Enable motion detection alerts",
        "  9. Regularly audit camera access logs",
        " 10. Apply patches for known CVEs immediately",
        "",
        "=" * 70,
        "  Generated by CCTVGuard v1.0 — SOC Portfolio Tool",
        "  github.com/muhammed95rafi-arch",
        "=" * 70,
    ]
    with open(path, "w") as f:
        f.write("\n".join(lines))


def _write_html(path, target, cameras, vulns, passwords, score, ts):
    level = _risk_level(score)
    risk_color = "#dc2626" if score >= 30 else "#ea580c" if score >= 20 else "#ca8a04"
    sev_color  = {"CRITICAL": "#dc2626", "HIGH": "#ea580c", "MEDIUM": "#ca8a04", "LOW": "#16a34a", "INFO": "#2563eb"}

    cam_rows = ""
    for cam in cameras:
        cam_rows += f"""
        <tr>
          <td><strong>{cam['ip']}</strong></td>
          <td>{cam['brand']}</td>
          <td>{', '.join(map(str, cam['open_ports']))}</td>
          <td>{'<span style="color:#dc2626">YES</span>' if cam['rtsp_available'] else 'No'}</td>
          <td>{'YES' if cam['has_web_interface'] else 'No'}</td>
        </tr>"""

    vuln_rows = ""
    for v in vulns:
        color  = sev_color.get(v["severity"], "#6b7280")
        status = "VULNERABLE" if v["status"] == "FAIL" else ("PROTECTED" if v["status"] == "PASS" else "INFO")
        s_col  = "#dc2626" if v["status"] == "FAIL" else "#16a34a"
        vuln_rows += f"""
        <tr>
          <td><span style="color:{s_col};font-weight:bold">{status}</span></td>
          <td><span style="background:{color};color:white;padding:2px 8px;border-radius:12px;font-size:0.75rem">{v['severity']}</span></td>
          <td><strong>{v['title']}</strong></td>
          <td>{v['description']}</td>
        </tr>"""

    pass_status = "CRITICAL — Default credentials FOUND!" if passwords.get("vulnerable") else "PASS — No default credentials found"
    pass_color  = "#dc2626" if passwords.get("vulnerable") else "#16a34a"
    creds_found = ", ".join(passwords.get("credentials_found", [])) or "None"

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>CCTVGuard Report</title>
<style>
  *{{box-sizing:border-box;margin:0;padding:0}}
  body{{font-family:'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0}}
  .header{{background:linear-gradient(135deg,#1e293b,#0f172a);border-bottom:2px solid #dc2626;padding:30px 40px}}
  .header h1{{font-size:2rem;color:#dc2626;letter-spacing:2px}}
  .header p{{color:#94a3b8;margin-top:6px}}
  .meta{{display:flex;gap:20px;margin-top:20px;flex-wrap:wrap}}
  .meta-item{{background:#1e293b;padding:10px 20px;border-radius:8px;border-left:3px solid #dc2626}}
  .meta-item label{{font-size:0.75rem;color:#64748b;text-transform:uppercase}}
  .meta-item span{{display:block;font-size:1.1rem;font-weight:bold;color:{risk_color}}}
  .container{{max-width:1100px;margin:30px auto;padding:0 20px}}
  .section{{background:#1e293b;border-radius:12px;margin-bottom:30px;border:1px solid #334155;overflow:hidden}}
  .section-header{{background:#0f172a;padding:16px 24px;border-bottom:1px solid #334155}}
  .section-header h2{{color:#38bdf8;font-size:1.1rem}}
  table{{width:100%;border-collapse:collapse}}
  th{{background:#0f172a;padding:12px 16px;text-align:left;font-size:0.8rem;color:#64748b;text-transform:uppercase}}
  td{{padding:12px 16px;border-bottom:1px solid #334155;font-size:0.9rem;vertical-align:top}}
  tr:last-child td{{border-bottom:none}}
  tr:hover{{background:#0f172a}}
  .rec-list{{padding:20px 24px}}
  .rec-list li{{padding:8px 0;border-bottom:1px solid #334155;color:#cbd5e1;list-style:none}}
  .rec-list li::before{{content:"→ ";color:#38bdf8;font-weight:bold}}
  .footer{{text-align:center;padding:20px;color:#475569;font-size:0.85rem}}
</style>
</head>
<body>
<div class="header">
  <h1>🎥 CCTVGuard</h1>
  <p>CCTV Security Assessment Report</p>
  <div class="meta">
    <div class="meta-item"><label>Target</label><span style="color:#e2e8f0;font-size:0.9rem">{target}</span></div>
    <div class="meta-item"><label>Risk Score</label><span>{score}/100</span></div>
    <div class="meta-item"><label>Risk Level</label><span>{level}</span></div>
    <div class="meta-item"><label>Date</label><span style="color:#e2e8f0;font-size:0.9rem">{ts}</span></div>
  </div>
</div>
<div class="container">
  <div class="section">
    <div class="section-header"><h2>1. Cameras Discovered</h2></div>
    <table>
      <tr><th>IP Address</th><th>Brand</th><th>Open Ports</th><th>RTSP</th><th>Web UI</th></tr>
      {cam_rows if cam_rows else '<tr><td colspan="5" style="text-align:center;color:#64748b">No cameras discovered</td></tr>'}
    </table>
  </div>
  <div class="section">
    <div class="section-header"><h2>2. Vulnerability Findings</h2></div>
    <table>
      <tr><th>Status</th><th>Severity</th><th>Finding</th><th>Description</th></tr>
      {vuln_rows}
    </table>
  </div>
  <div class="section">
    <div class="section-header"><h2>3. Password Scan Results</h2></div>
    <table>
      <tr><th>Status</th><th>Credentials Found</th></tr>
      <tr>
        <td style="color:{pass_color};font-weight:bold">{pass_status}</td>
        <td>{creds_found}</td>
      </tr>
    </table>
  </div>
  <div class="section">
    <div class="section-header"><h2>4. Recommendations</h2></div>
    <ul class="rec-list">
      <li>Change all default credentials immediately — use strong unique passwords</li>
      <li>Update camera firmware to latest version — patches known CVEs</li>
      <li>Disable Telnet, FTP, and unused network services</li>
      <li>Enable HTTPS only — disable plain HTTP access</li>
      <li>Use VPN for remote access instead of port forwarding</li>
      <li>Segment CCTV cameras on a separate VLAN</li>
      <li>Disable UPnP to prevent automatic internet exposure</li>
      <li>Enable and review camera access logs regularly</li>
      <li>Apply patches for CVE-2021-36260, CVE-2017-7921 immediately</li>
      <li>Disable RTSP if remote streaming is not required</li>
    </ul>
  </div>
</div>
<div class="footer">Generated by CCTVGuard v1.0 — SOC Portfolio | github.com/muhammed95rafi-arch</div>
</body>
</html>"""

    with open(path, "w") as f:
        f.write(html)